services:
  database:
    image: postgres:17
    container_name: app-contacts-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  test-database:
    image: postgres:17
    container_name: app-contacts-test-db
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${TEST_POSTGRES_USER} -d ${TEST_POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: fehizor0/app-contacts-backend:${IMAGE_TAG:-latest}
    build:
      context: ./backend
    container_name: app-contacts-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    depends_on:
      database:
        condition: service_healthy

  backend-test:
    build:
      context: ./backend
    container_name: app-contacts-backend-test
    environment:
      DATABASE_URL: postgresql+psycopg://${TEST_POSTGRES_USER}:${TEST_POSTGRES_PASSWORD}@test-database:5432/${TEST_POSTGRES_DB}
    depends_on:
      test-database:
        condition: service_healthy

  frontend:
    image: fehizor0/app-contacts-frontend:${IMAGE_TAG:-latest}
    build:
      context: ./frontend
    container_name: app-contacts-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  db-data:
  test-db-data:
