---
- name: Déploiement de app-contacts
  hosts: target
  become: false

  vars:
    project_dir: /home/fehizoro/app-contacts
    git_commit: main

  tasks:
    - name: Récupérer le projet depuis GitHub au commit voulu
      ansible.builtin.git:
        repo: "https://github.com/FehiZor0/app-contacts.git"
        dest: "{{ project_dir }}"
        version: "{{ git_commit }}"
        force: true

    - name: Déployer l'application avec Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        build: always
        state: present

    - name: Vérifier que le backend est disponible
      ansible.builtin.uri:
        url: http://localhost:8000/health
        status_code: 200
        return_content: true
      register: backend_health
      retries: 10
      delay: 3
      until: backend_health.status | default(0) == 200

    - name: Vérifier que le frontend est disponible
      ansible.builtin.uri:
        url: http://localhost:8081
        status_code: 200
      register: frontend_health
      retries: 10
      delay: 3
      until: frontend_health.status | default(0) == 200

    - name: Afficher le résultat du healthcheck backend
      ansible.builtin.debug:
        msg: "Backend opérationnel : {{ backend_health.json }}"

    - name: Afficher le résultat du healthcheck frontend
      ansible.builtin.debug:
        msg: "Frontend opérationnel avec le code HTTP {{ frontend_health.status }}"
